"""add_purge_calibration_table

Creates the purge_calibration table with all its columns, indexes,
and foreign key constraints to the filament table.

Revision ID: 74c29f7bd37e
Revises: 415a8f855e14
Create Date: 2026-02-17 19:08:06.681758
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '74c29f7bd37e'
down_revision = '415a8f855e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purge_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('from_filament_id', sa.Integer(), nullable=False),
    sa.Column('to_filament_id', sa.Integer(), nullable=False),
    sa.Column('purge_volume', sa.Float(), nullable=False),
    sa.Column('multiplication_factor', sa.Float(), nullable=False),
    sa.Column('nozzle_size', sa.Float(), nullable=False),
    sa.Column('print_temp', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['from_filament_id'], ['filament.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_filament_id'], ['filament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purge_calibration_from_filament_id'), 'purge_calibration', ['from_filament_id'], unique=False)
    op.create_index(op.f('ix_purge_calibration_id'), 'purge_calibration', ['id'], unique=False)
    op.create_index(op.f('ix_purge_calibration_to_filament_id'), 'purge_calibration', ['to_filament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purge_calibration_to_filament_id'), table_name='purge_calibration')
    op.drop_index(op.f('ix_purge_calibration_id'), table_name='purge_calibration')
    op.drop_index(op.f('ix_purge_calibration_from_filament_id'), table_name='purge_calibration')
    op.drop_table('purge_calibration')
    # ### end Alembic commands ###
